/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bingis_khan.shitty_roguelike;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
